### ISSUE TITLE
Reimplement in TypeScript?

### ISSUE THREAD

**Issue by pllim** [stefanv/attach-next-milestone#5]
You might be able to take advantage of browser-native functionality that GitHub provides, like https://github.com/octokit/action.js/

The downside is that maintainer needs to touch JS.

**Comment by stefanv** [comment]
Yes, I think for our community it makes more sense to keep things in Python.

**Comment by pllim** [comment]
Okay, if irrelevant, feel free to close as "won't fix". Thanks!
